server:
  port: 8020

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall_commodity?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 111
    druid:
          initial-size: 1 #初始化物理连接个数
          max-active: 20 #最大连接池数量
          min-idle: 5 #最小连接池数量
          max-wait: 60000 #获取连接时最大连接时间（ms）
          pool-prepared-statements: true #开启缓存PreparedStatements
          #检测连接是否有效
          validation-query: 'x'
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
      name: mall-commodity

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
feign:
  client:
    config:
      mall-user:
        requestInterceptors:
          - com.worm.commodity.interceptor.FeignHeaderInterceptor

